python  ./pwb.py transferbot -lang:en -tolang:en -tofamily:speedydeletion  -family:wikipedia '-catr:Articles for deletion'
python  ./pwb.py transferbot -lang:zh -tolang:zh -tofamily:speedydeletion  -family:wikipedia '-catr:条目删除候选'
python  ./pwb.py transferbot -lang:it -tolang:it -tofamily:speedydeletion  -family:wikipedia '-catr:Pagine in cancellazione per argomento'
python  ./pwb.py transferbot -lang:es -tolang:es -tofamily:speedydeletion  -family:wikipedia '-catr:Wikipedia:Consultas de borrado'
python  ./pwb.py transferbot -lang:ru -tolang:ru -tofamily:speedydeletion  -family:wikipedia '-catr:Википедия:Кандидаты на удаление'
python  ./pwb.py transferbot -lang:nl -tolang:nl -tofamily:speedydeletion  -family:wikipedia '-catr:Wikipedia:Pagina weg'
python  ./pwb.py transferbot -lang:pt -tolang:pt -tofamily:speedydeletion  -family:wikipedia '-catr:!Páginas para eliminar'
python  ./pwb.py transferbot -lang:fr -tolang:fr -tofamily:speedydeletion  -family:wikipedia '-catr:Page proposée à la suppression'
python  ./pwb.py transferbot -lang:fa -tolang:fa -tofamily:speedydeletion  -family:wikipedia '-catr:مقاله‌های نامزد حذف'
python  ./pwb.py transferbot -lang:ja -tolang:ja -tofamily:speedydeletion  -family:wikipedia '-catr:削除依頼中のページ'
python  ./pwb.py transferbot -lang:sq -tolang:sq -tofamily:speedydeletion  -family:wikipedia '-catr:Faqe për grisje'
python  ./pwb.py transferbot -lang:sv -tolang:sv -tofamily:speedydeletion  -family:wikipedia '-catr:Sidor föreslagna för radering'
python  ./pwb.py transferbot -lang:uk -tolang:uk -tofamily:speedydeletion  -family:wikipedia '-catr:Статті-кандидати на вилучення'
python  ./pwb.py transferbot -lang:en -tolang:en -tofamily:speedydeletion  -family:wikipedia '-catr:Candidates for speedy deletion'
python  ./pwb.py transferbot -lang:zh -tolang:zh -tofamily:speedydeletion  -family:wikipedia '-catr:快速删除候选'
python  ./pwb.py transferbot -lang:vi -tolang:vi -tofamily:speedydeletion  -family:wikipedia '-catr:Chờ xóa'
python  ./pwb.py transferbot -lang:it -tolang:it -tofamily:speedydeletion  -family:wikipedia '-catr:Cancellare subito'
python  ./pwb.py transferbot -lang:es -tolang:es -tofamily:speedydeletion  -family:wikipedia '-catr:Wikipedia:Borrar (definitivo)'
python  ./pwb.py transferbot -lang:ru -tolang:ru -tofamily:speedydeletion  -family:wikipedia '-catr:Википедия:К быстрому удалению'
python  ./pwb.py transferbot -lang:nl -tolang:nl -tofamily:speedydeletion  -family:wikipedia '-catr:Wikipedia:Nuweg'
python  ./pwb.py transferbot -lang:pt -tolang:pt -tofamily:speedydeletion  -family:wikipedia '-catr:!Páginas para eliminação rápida'
python  ./pwb.py transferbot -lang:no -tolang:no -tofamily:speedydeletion  -family:wikipedia '-catr:Sider som er foreslått raskt slettet'
python  ./pwb.py transferbot -lang:war -tolang:war -tofamily:speedydeletion  -family:wikipedia '-catr:Candidates for speedy deletion'
python  ./pwb.py transferbot -lang:pl -tolang:pl -tofamily:speedydeletion  -family:wikipedia '-catr:Ekspresowe kasowanie'
python  ./pwb.py transferbot -lang:fr -tolang:fr -tofamily:speedydeletion  -family:wikipedia '-catr:Wikipédia:Suppression immédiate demandée'
python  ./pwb.py transferbot -lang:ceb -tolang:ceb -tofamily:speedydeletion  -family:wikipedia '-catr:Kandidato sa pagtangtang dayon'
python  ./pwb.py transferbot -lang:de -tolang:de -tofamily:speedydeletion  -family:wikipedia '-catr:Wikipedia:Schnelllöschen'
python  ./pwb.py transferbot -lang:fa -tolang:fa -tofamily:speedydeletion  -family:wikipedia '-catr:مقاله‌های نامزد حذف سریع'
python  ./pwb.py transferbot -lang:fi -tolang:fi -tofamily:speedydeletion  -family:wikipedia '-catr:Pikapoisto'
python  ./pwb.py transferbot -lang:ja -tolang:ja -tofamily:speedydeletion  -family:wikipedia '-catr:即時削除対象のページ'
python  ./pwb.py transferbot -lang:sr -tolang:sr -tofamily:speedydeletion  -family:wikipedia '-catr:Брзо брисање'
python  ./pwb.py transferbot -lang:sv -tolang:sv -tofamily:speedydeletion  -family:wikipedia '-catr:Snabbraderingar'
python  ./pwb.py transferbot -lang:uk -tolang:uk -tofamily:speedydeletion  -family:wikipedia '-catr:Статті до швидкого вилучення'
python  ./pwb.py transferbot -lang:en -tolang:en -tofamily:speedydeletion  -family:wikipedia '-catr:Proposed deletion'
python  ./pwb.py transferbot -lang:es -tolang:es -tofamily:speedydeletion  -family:wikipedia '-catr:Wikipedia:Propuestas de borrado'
python  ./pwb.py transferbot -lang:ru -tolang:ru -tofamily:speedydeletion  -family:wikipedia '-catr:Википедия:Страницы к удалению'
python  ./pwb.py transferbot -lang:pt -tolang:pt -tofamily:speedydeletion  -family:wikipedia '-catr:!Páginas para eliminação semirrápida'
python  ./pwb.py transferbot -lang:fa -tolang:fa -tofamily:speedydeletion  -family:wikipedia '-catr:صفحه‌های حذف زمان‌دار'
python  ./pwb.py transferbot -lang:ja -tolang:ja -tofamily:speedydeletion  -family:wikipedia '-catr:提案削除'
